### ISSUE TITLE
[Feature Request] Implement copy button

### ISSUE THREAD

**Issue by fuuga-2915** [Olaren15/ffxiv-easy-translate#31]
Hello! Thank you for creating such a great plugin. 
I thought it would be much easier to use if you could add a "Copy" button next to the words in the search results, so that you could copy the words to the clipboard.

**Comment by Olaren15** [comment]
Thanks for the suggestion! That is a great idea. I'll definitely add this in a future version :)

**Comment by Olaren15** [comment]
Look forward to see this feature in the next release of EasyTranslate!

**Comment by fuuga-2915** [comment]
Thank you for implementing it!
I'm looking forward to its release XD
